### ISSUE TITLE
Which license?

### ISSUE THREAD

**Issue by matryer** [nf/cr2#4]
Thanks for making this package, it's great.

Have you given any thought to which LICENSE will this project have, if any?

I can submit a PR to add the `LICENSE` file for you to save your time?

**Comment by nf** [comment]
Same as Go: https://golang.org/LICENSE

Your PR would be welcome.

Thanks.

**Comment by matryer** [comment]
@nf https://github.com/nf/cr2/pull/5

**Comment by nf** [comment]
A'thankya!
